//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyJobPortalEntities : DbContext
    {
        public MyJobPortalEntities()
            : base("name=MyJobPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMst> AdminMsts { get; set; }
        public virtual DbSet<CompanyMst> CompanyMsts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dist> Dists { get; set; }
        public virtual DbSet<PostJobMst> PostJobMsts { get; set; }
        public virtual DbSet<SekerMst> SekerMsts { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Taluka> Talukas { get; set; }
        public virtual DbSet<TblAddress> TblAddresses { get; set; }
        public virtual DbSet<TblCity> TblCities { get; set; }
        public virtual DbSet<TblCompany> TblCompanies { get; set; }
        public virtual DbSet<TblCompanyMessageRecived> TblCompanyMessageReciveds { get; set; }
        public virtual DbSet<TblCompanyMessageSend> TblCompanyMessageSends { get; set; }
        public virtual DbSet<TblCountry> TblCountries { get; set; }
        public virtual DbSet<TblDist> TblDists { get; set; }
        public virtual DbSet<TblEndustry> TblEndustries { get; set; }
        public virtual DbSet<TblImage> TblImages { get; set; }
        public virtual DbSet<TblJobApplication> TblJobApplications { get; set; }
        public virtual DbSet<TblJobPost> TblJobPosts { get; set; }
        public virtual DbSet<TblJobSaved> TblJobSaveds { get; set; }
        public virtual DbSet<TblPosition> TblPositions { get; set; }
        public virtual DbSet<TblProfileViewed> TblProfileVieweds { get; set; }
        public virtual DbSet<TblState> TblStates { get; set; }
        public virtual DbSet<TblUserMessageRecived> TblUserMessageReciveds { get; set; }
        public virtual DbSet<TblUserMessageSend> TblUserMessageSends { get; set; }
        public virtual DbSet<TblUserType> TblUserTypes { get; set; }
        public virtual DbSet<EdgucationMst> EdgucationMsts { get; set; }
        public virtual DbSet<TblDepartment> TblDepartments { get; set; }
        public virtual DbSet<TblHighestQualification> TblHighestQualifications { get; set; }
        public virtual DbSet<TblEducationType> TblEducationTypes { get; set; }
        public virtual DbSet<TblEducation> TblEducations { get; set; }
        public virtual DbSet<TblYear> TblYears { get; set; }
        public virtual DbSet<TblAnualInLakhSalery> TblAnualInLakhSaleries { get; set; }
        public virtual DbSet<TblAnualSaleryInThousent> TblAnualSaleryInThousents { get; set; }
        public virtual DbSet<TblExpreance> TblExpreances { get; set; }
        public virtual DbSet<TblEmployement> TblEmployements { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblSkillSet> TblSkillSets { get; set; }
        public virtual DbSet<TblProfileSummery> TblProfileSummeries { get; set; }
        public virtual DbSet<TblResume> TblResumes { get; set; }
        public virtual DbSet<TblProject> TblProjects { get; set; }
    }
}
