//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJobMst
    {
        public int JobId { get; set; }
        public Nullable<int> Cid { get; set; }
        public string JobCategory { get; set; }
        public string RequireSkill { get; set; }
        public Nullable<int> ExprienceRequire { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string PostDiscription { get; set; }
    }
}
