//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExpreance
    {
        public int ExprenceId { get; set; }
        public Nullable<int> ExpreanceInMonth { get; set; }
        public Nullable<int> ExpreanceInYear { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
