//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int EdgucationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EducationType { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public string CollageName { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> SkillSetId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PassingMonth { get; set; }
        public Nullable<int> PassingYear { get; set; }
    }
}
