//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployement
    {
        public int EmployementId { get; set; }
        public Nullable<bool> IscurrentCompany { get; set; }
        public Nullable<int> SkillSetId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> LocationDisrictId { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public string NoticePeriod { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> UearId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> AnualSaleryInLakh { get; set; }
        public Nullable<int> AnualSaleryInThousent { get; set; }
        public string SaleryIn { get; set; }
    }
}
