//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblJobPost
    {
        public int JobPostId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> JobCategory { get; set; }
        public Nullable<int> JobPosition { get; set; }
        public string JobDisctiption { get; set; }
        public Nullable<int> NoticePerionInDays { get; set; }
        public Nullable<int> NoticePeriodInMonth { get; set; }
        public Nullable<int> SaleryRs { get; set; }
        public Nullable<int> SaleryDoller { get; set; }
        public Nullable<int> Exprience { get; set; }
        public Nullable<int> PostionOpen { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
